# Generated by Django 3.1.3 on 2022-02-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('speed', models.CharField(default='', max_length=300)),
                ('temp', models.CharField(default='', max_length=300)),
                ('fuel_level', models.CharField(default='', max_length=300)),
                ('engine_status', models.CharField(default='', max_length=300)),
                ('start', models.BooleanField(default=False)),
            ],
        ),
    ]
