# Generated by Django 3.1.3 on 2022-02-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_guide', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complain',
            new_name='Vehicle',
        ),
    ]
